spring.application.name=stc

#  when you want to run the project in local ( without docker )
# spring.profiles.active=dev

# ==============================
# Database
# ==============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# Cloudinary
# ==============================
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}

# ==============================
# Redis
# ==============================

# local redis server 
# spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
# spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# for depployment 
spring.data.redis.url=${SPRING_DATA_REDIS_URL}